### ISSUE TITLE
Can you remove the pwn.college writeups?

### ISSUE THREAD

**Issue by zardus** [manesec/manesec.github.io#1]
Hello,

Someone pointed your site out to me as having public pwn.college writeups at https://manesec.github.io/2024/07/25/2024/0725-pwn-college-Assembly-Crash-Course-Solution/. Our writeup policy requests that you refrain from posting public writeups, as we use pwn.college in courses at ASU (and beyond), and available writeups compromise this for us. Could you remove the pwn.college writeups?

**Comment by manesec** [comment]
sure, I will make it password protect, thanks for contacting me.

**Comment by zardus** [comment]
Thanks!
